author = "Walnut356"
base_url = "https://walnut356.github.io"
description = ""
title = "Cracking the Shell"

compile_sass = true
default_language = "en"
feed_filename = "atom.xml"
generate_feed = true
minify_html = true

build_search_index = false

theme = "papermod"

taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
external_links_target_blank = true
extra_syntaxes_and_themes = ["syntaxes"]
highlight_code = true
highlight_theme = "css"
highlight_theme_css = [{ theme = "temp", filename = "syntax-theme.css" }]


[extra.papermod]
default_theme = "dark"
default_toc_open = true
edit_post_url = "https://github.com/Walnut356/Walnut356.github.io"
keywords = [""]
language_direction = "auto"
show_code_copy_buttons = true
show_post_edit_button = false
show_post_meta = true
show_post_nav_links = true
show_reading_time = true
show_scroll_to_top = true
show_theme_toggle = true
show_word_count = true
theme = "dark"
title = "Cracking The Shell"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
]

home_content = "Self taught developer. Interested in systems programming, video games, and epic fantasy books."
home_title = "A Walnut's Thoughts"
social_icons = [
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
    { url = "https://github.com/walnut356", title = "GitHub", icon = "github" },
]
