author = "Walnut356"
base_url = "https://walnut356.github.io"
description = ""
title = "Cracking the Shell"

compile_sass = true
default_language = "en"
feed_filenames = ["atom.xml"]
generate_feeds = true
minify_html = true

build_search_index = true

theme = "papermod"

taxonomies = [{ name = "tags", feed = true }]

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100
# Wether to produce the search index as a javascript file or as a JSON file
# Accepted value "elasticlunr_javascript" or "elasticlunr_json"
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
external_links_target_blank = true
extra_syntaxes_and_themes = ["syntaxes"]
highlight_code = true
highlight_theme = "css"
highlight_theme_css = [{ theme = "temp", filename = "syntax-theme.css" }]


[extra.papermod]
default_theme = "dark"
default_toc_open = false
edit_post_url = "https://github.com/Walnut356/Walnut356.github.io"
keywords = [""]
language_direction = "auto"
show_code_copy_buttons = true
show_post_edit_button = false
show_post_meta = true
show_post_nav_links = true
show_reading_time = true
show_scroll_to_top = true
show_theme_toggle = true
show_word_count = true
theme = "dark"
title = "Cracking The Shell"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/search", title = "Search" },
    { url = "$BASE_URL/tags", title = "Tags" },
]

home_content = """My name is Anthony, I'm a self taught developer based in the midwest. I'm interested in systems programming, dev tools, and game design. Currently looking for work.
<br>
<br>
3 miles deep in the Rust debugging rabbit hole. If you have any questions regarding that, feel free to send me an email or a message in the Rust zulip or LLVM discourse.
<br>
<br>
I love epic fantasy novels, my favorites are Malazan Book of the Fallen and The Wheel of Time. Currently reading The Black Company."""
home_title = "A Walnut's Thoughts"
social_icons = [
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
    { url = "https://github.com/walnut356", title = "GitHub", icon = "github" },
    { url = "mailto:walnut356dev@gmail.com", title = "Email", icon = "email" },
]
